class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

## All of the methods are the default methods generated by rails for a model

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # Reboot the app. Delete all nominees and reset members' voted row to nil
  def appReboot
    @members = Member.all
    auth_mail = params["email"] 
    auth_password = params["password"]
    @valid_mail = false
    @auth_error = false
    if auth_mail == "denise@cmu.edu"
      puts "**************************** Email Validated ******************"
      if auth_password == "Admin1020!"
        @valid_mail = true
        puts "**************************** Password OK - Authorization Granted ******************"
        puts @valid_mail
      end
    end

  end

  def totalRecall
    @members = Member.all
    @nominees = Nominee.all
    puts "**************************** Everything Deleted ******************"
    @nominees.destroy_all
    @members.update_all(:voted => nil)
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:mail)
    end
end
